HOSTNAME="rancher.hvst-vip.aegisgroup.ch"
BOOTSTRAP_PW="admin1234567"
PVC_SIZE="40Gi"
STORAGE_CLASS="harvester-longhorn"
SERVER_COUNT=3
TLS_SOURCE="secret"
PRIVATE_REGISTRY=""
PRIVATE_CA_PATH=""
CA_CERT_PATH="/home/rocky/code/PKI/intermediates/k3k-signing/k3k-signing-ca.pem"
CA_KEY_PATH="/home/rocky/code/PKI/intermediates/k3k-signing/k3k-signing-ca-key.pem"
CA_ROOT_PATH="/home/rocky/code/PKI/roots/aegis-group-root-ca.pem"
RANCHER_VERSION="v2.13.3"
CONFIRM="yes"
